### ISSUE TITLE
anonymous classes

### ISSUE THREAD

**Issue by yorrd** [vegarringdal/custom-elements-hmr-polyfill#40]
Hi :) thanks for the awesome polyfill. One problem left for us:

We have standard components (where the polyfill works like a charm) and then we have generated components. With those, the polyfill doesn't work. Here's our definition:

```ts

export const createEmotionComponent = (name: string, baseStyle: Interpolation) => {
  customElements.define(
    name,
    class extends OurEmotionBaseClass {
      // ... some emotion magic

      public render() {
        return html`
          this is never rendered
          <slot></slot>
        `;
      }
    },
  );

  return customElements.get(name);
};

```

Those components render without content, as if the render method is ignored. I do see logs in that method though. `OurEmotionBaseClass` is a class that we use in other working components that are not generated through a function.

Are you aware of this? Any ideas on how to troubleshoot this?

**Comment by yorrd** [comment]
please ignore this, we just rendered too early (before the polyfill) I think. Is it possible that this happens when timing isn't right? 

Do you think it's a good idea to throw an exception in the polyfill if there are already components defined before it's loaded?

**Comment by vegarringdal** [comment]
When hmr event happends all elements should get their `disconnectedCallback` called, so they clean up listeners etc.
So I guess best way to use it would be to have 1 main component, and just reset this so you start up like a fresh page.

1:  restore state
2:  clear body and set back main root element so everything can rerender

```js
if (document.body) {
        document.body.innerHTML = ''; // this will trigger disconnectedCallback
        document.body.innerHTML = '<root-app></root-app>'; // will rerender page, usually this
}
```

If any element isnt able to clean up then this will fail fast I guess. :-)


> Do you think it's a good idea to throw an exception in the polyfill if there are already components defined before it's loaded?

Maybe I could add a check for first time, would need to store what been used before etc, since whole point with pollyfill it to allow it to be redefined.

But trying to redefine a custom element without the pollyfill will throw error, so I though everyone checked for this...

In my wrapper lib around lit-html I do this:
```js
if (!customElements.get(elementName)) {
            customElements.define(elementName, Base);
        } else {
            if ((globalThis as any).hmrCache) {
                customElements.define(elementName, Base);
            }
        }
```
So in production build where pollyfill isnt there I never define it more then once..

**Comment by yorrd** [comment]
thanks for the clarification!
